### ISSUE TITLE
Exception thrown when creating byte property value

### ISSUE THREAD

**Issue by roryprimrose** [roryprimrose/ModelBuilder#168]
```

System.ArgumentException
Object of type 'System.Int32' cannot be converted to type 'System.Byte'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at ModelBuilder.DefaultExecuteStrategy.PopulateProperty(PropertyInfo propertyInfo, Object instance, Object[] args)
   at ModelBuilder.DefaultExecuteStrategy.AutoPopulateInstance(Object instance, Object[] args)
   at ModelBuilder.DefaultExecuteStrategy.Populate(IBuildCapability capability, Object instance, Object[] args)
   at ModelBuilder.DefaultExecuteStrategy.Build(Func`1 getCapability, Func`3 buildInstance, Type type, Object[] args)
   at ModelBuilder.DefaultExecuteStrategy.Build(Type type, Object[] args)
```

**Comment by roryprimrose** [comment]
The issue was caused by a creation rule extension method providing the literal int 1 as the value for a byte property

**Comment by roryprimrose** [comment]
This is not an issue with the current code.

```csharp
        [Fact]
        public void CreateCanPopulateByteProperty()
        {
            // Validates https://github.com/roryprimrose/ModelBuilder/issues/168 and found not to be an issue in the current code
            var actual = Model.WriteLog<PropertyModel<byte>>(_output.WriteLine).Create();

            _output.WriteLine(actual.Value.ToString());
        }
```

```
Start creating type ModelBuilder.UnitTests.Models.PropertyModel`1[[System.Byte, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] using ModelBuilder.TypeCreators.DefaultTypeCreator
    Start populating instance ModelBuilder.UnitTests.Models.PropertyModel`1[[System.Byte, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
        Creating property Value (System.Byte) on type ModelBuilder.UnitTests.Models.PropertyModel`1[[System.Byte, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
            Start creating type System.Byte using ModelBuilder.ValueGenerators.NumericValueGenerator
            End creating type System.Byte
        Created property Value (System.Byte) on type ModelBuilder.UnitTests.Models.PropertyModel`1[[System.Byte, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
    End populating instance ModelBuilder.UnitTests.Models.PropertyModel`1[[System.Byte, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
End creating type ModelBuilder.UnitTests.Models.PropertyModel`1[[System.Byte, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]

104
```
