### ISSUE TITLE
Build throws ArgumentOutOfRangeException using StringBuilder

### ISSUE THREAD

**Issue by roryprimrose** [roryprimrose/ModelBuilder#25]
The following exception was thrown building a class.

```
System.ArgumentOutOfRangeException
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: chunkLength
   at System.Text.StringBuilder.ToString()
   at ModelBuilder.DefaultExecuteStrategy.Build(Type type, String referenceName, Object context, Object[] args) in C:\Repos\ModelBuilder\ModelBuilder\DefaultExecuteStrategy.cs:line 198
   at ModelBuilder.DefaultExecuteStrategy`1.CreateWith(Object[] args) in C:\Repos\ModelBuilder\ModelBuilder\DefaultExecuteStrategyT.cs:line 22
```

**Comment by roryprimrose** [comment]
The issue here is that StringBuilder is not thread safe and the BuildLog is not unique to a Model.Create call.
